### ISSUE TITLE
asyncio trouble with `WorkloadIdentity` 

### ISSUE THREAD

**Issue by brews** [RhodiumGroup/rhg_pulumi_resources#5]
Provisioning with `rpr.gcp.WorkloadIdentity` raises an error, like:

```
   pulumi:pulumi:Stack (crs-waterworks-cluster-prod):
     error: Program failed with an unhandled exception:
     error: Traceback (most recent call last):
       File "/root/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
         loop.run_until_complete(coro)
       File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
         return future.result()
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
         await run_pulumi_func(lambda: Stack(func))
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 50, in run_pulumi_func
         await RPC_MANAGER.rpcs.pop()
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
         result = await rpc
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 89, in is_value_known
         return await is_known and not contains_unknowns(await future)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 89, in is_value_known
         return await is_known and not contains_unknowns(await future)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 89, in is_value_known
         return await is_known and not contains_unknowns(await future)
       [Previous line repeated 4 more times]
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 325, in do_register
         resolver = await prepare_resource(res, ty, custom, props, opts)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 88, in prepare_resource
         serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 68, in serialize_properties
         result = await serialize_property(v, deps, input_transformer)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 173, in serialize_property
         value = await serialize_property(output.future(), deps, input_transformer)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
         future_return = await asyncio.ensure_future(awaitable)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 114, in get_value
         val = await self._future
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 155, in run
         value = await self._future
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 340, in gather_futures
         return await asyncio.gather(*value_futures)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 114, in get_value
         val = await self._future
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 155, in run
         value = await self._future
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 176, in run
         transformed: Input[U] = func(value)
       File "/opt/conda/lib/python3.8/site-packages/pulumi/output.py", line 235, in <lambda>
         return self.apply(lambda v: UNKNOWN if isinstance(v, Unknown) else cast(Any, v)[key], True)
     KeyError: 'namespace'
     error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

I've seen this while provisioning the waterworks cluster and fastimpact cluster.

The workaround has been to remove, or comment out resources related to the WorkloadIdentity, run the update, then uncomment the resources and run the update again.

**Comment by brews** [comment]
Maybe related to upstream https://github.com/pulumi/pulumi/issues/4040
